SITES-11252: Limit formatting options for RTE editor (e.g., only bold…
adobe/aem-uix-examples pull request #20
Opened 2024-02-13 23:26 UTC by irenelagno

… allowed)

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-02-14 09:06 UTC, fe-lix- approved these changes
LGTM

2024-02-14 09:06 UTC, fe-lix- commented on cf-editor-rte-toolbar-configurable-buttons/src/aem-cf-editor-1/web-src/src/utils.js
> +export const getContentFragmentConfig = async (token, imsOrg) => {
This should be `getContentFragmentModelConfig`.

2024-02-14 09:06 UTC, fe-lix- commented on cf-editor-rte-toolbar-configurable-buttons/src/aem-cf-editor-1/actions/getCFModelConfig/index.js
> +    const inputString = "aligncenter | alignjustify | alignleft | alignnone | alignright | blockquote | backcolor | bold | copy | cut | fontselect | fontsizeselect | forecolor | formatselect | h1 | h
Yes, that's exactly what I had in mind. To have a list in a parsable format. The only problem with your implementation is due to our current API. We can only remove and state what toolbar we actually want but this looks great.

I would assume the string coming from the CFM metadata would be JSON, but that's a minor detail.

2024-04-09 20:09 UTC, lenaorobei requested changes
Please clean up unused code and add license headers to the files.

2024-04-09 20:09 UTC, lenaorobei commented on cf-editor-rte-toolbar-configurable-buttons/README.md
> +Welcome to my Adobe I/O Application!
Can you please add more details on how this extension works? Thanks!

2024-04-09 20:09 UTC, lenaorobei commented on cf-editor-rte-toolbar-configurable-buttons/src/dx-excshell-1/web-src/src/index.js
> +/*
This file can be as simple as

``` js
import "core-js/stable";

window.React = require("react");
import ReactDOM from "react-dom";

import App from "./components/App";

ReactDOM.render(<App />, document.getElementById("root"));
```

2024-04-17 19:39 UTC, irenelagno commented
@lenaorobei fixed. Please check

2024-04-17 19:42 UTC, lenaorobei approved these changes

2024-04-17 19:48 UTC, merged