SITES-22608 Add Universal Editor Reach text drafts manager extension
adobe/aem-uix-examples pull request #38
Opened 2024-06-21 09:58 UTC by ahajji87

## Description
Jira task: https://jira.corp.adobe.com/browse/SITES-22608
This extension is for the Universal Editor tool. It allows the user to manage drafts for reachtext content.
The extension is to add the rail.

**Feature**
- Draft Management: Create multiple drafts of a reach text content.
- Draft Preview: Each draft can be previewed within the editor. This allows users to review their drafts before finalizing their content.
- Draft Actions: Users can perform several actions on each draft, including reverting changes, adding a new draft, selecting a draft, saving a draft, and deleting a draft.

**Demo:**
To test the extension, add this to your universal editor site: ?ext=https://245265-aminetestextensions-stage.adobeio-static.net/index.html

There is also this site (in case you have permission):  [xwalk-extensibility-playground](https://author-p130360-e1272151.adobeaemcloud.com/ui#/@sitesinternal/aem/universal-editor/canvas/author-p130360-e1272151.adobeaemcloud.com/content/xwalk-extensibility-playground/index.html?ext=https://245265-aminetestextensions-stage.adobeio-static.net/index.html)

**Preview:**
![Screenshot 2024-06-21 at 11 29 49](https://github.com/adobe/aem-uix-examples/assets/5780769/e933c21d-15a5-4920-a2ca-8c6bfb766e72)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

2024-06-21 13:53 UTC, fe-lix- commented
Hey @ahajji87 this is a public repo. Let's only reference publicly accessible resources.

2024-06-21 17:39 UTC, lenaorobei commented on universal-editor-richtext-draft/README.md
> +# Universal Editor Rich Text Draft
I'd rename it to just "Content Drafts"
```suggestion
# Content Drafts
```

2024-06-21 17:40 UTC, lenaorobei commented on universal-editor-richtext-draft/extension-manifest.json
> +  "name": "Rich Text drafts manager",
```suggestion
  "name": "Content drafts",
```

2024-06-21 17:41 UTC, lenaorobei commented on universal-editor-richtext-draft/src/universal-editor-ui-1/web-src/src/components/ExtensionRegistration.js
> +                                header: "Manage Rich Texts drafts",
```suggestion
                                header: "Content drafts",
```

2024-06-21 17:45 UTC, lenaorobei commented on universal-editor-richtext-draft/src/universal-editor-ui-1/web-src/src/components/RichTextDraftsRail.js
> +import SaveToLight from "@spectrum-icons/workflow/SaveToLight";
Let's use "Checkmark Circle" icon and "Apply" text instead of "Save".

2024-06-21 17:46 UTC, lenaorobei commented on universal-editor-richtext-draft/src/universal-editor-ui-1/actions/save-draft/index.js
> +Copyright 2022 Adobe
```suggestion
Copyright 2024 Adobe
```

2024-06-21 17:46 UTC, lenaorobei commented on universal-editor-richtext-draft/jest.setup.js
> +* <license header>
Missing license, please check other files as well.

2024-06-21 17:47 UTC, lenaorobei commented on universal-editor-richtext-draft/src/universal-editor-ui-1/web-src/src/components/RichTextDraftsRail.js
> +                                        <Heading marginBottom='size-50' marginTop='size-50' level='4' isHidden={itemsDraftList.get(reachTextItem.id)?.length === 0}>Drafts list:</Heading>
```suggestion
                                        <Heading marginBottom='size-50' marginTop='size-50' level='4' isHidden={itemsDraftList.get(reachTextItem.id)?.length === 0}>Drafts</Heading>
```

2024-06-21 18:21 UTC, kokoc requested changes

2024-06-21 18:21 UTC, kokoc commented on universal-editor-richtext-draft/extension-manifest.json
> +  "headerMenuButtons": [
Not sure that this is relevant. I saw only rail ext point button in UI

2024-06-21 18:21 UTC, kokoc commented on universal-editor-richtext-draft/package.json
> +    "@adobe/uix-guest": "^0.8.0",
Let's use the latest version in the new extension. `0.10.3`

2024-06-25 08:46 UTC, ahajji87 commented on universal-editor-richtext-draft/README.md
> +- **Draft Preview**: Each draft can be previewed within the editor. This allows users to review their drafts before finalizing their content.
You can review the draft by clicking on it. On the list, we see a part of it, and after clicking on it, we see the entire draft. I will add it to the text.

2024-06-27 08:41 UTC, ahajji87 commented on universal-editor-richtext-draft/README.md
> +- **Draft Preview**: Each draft can be previewed within the editor. This allows users to review their drafts before finalizing their content.
Please, check the new changes, now we can edit the drafts and we show by default 3 drafts with a (show all) option

2024-06-28 21:42 UTC, kokoc approved these changes

2024-07-02 08:58 UTC, merged