Universal editor product picker
adobe/aem-uix-examples pull request #39
Opened 2024-06-27 17:10 UTC by naydav

## Description

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

2024-06-27 18:33 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ExtensionRegistration.js
> +                url: '/index.html#/product-field',
Need to move to configuration

2024-06-27 18:34 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductField.js
> +      await guestConnection.host.field.setStyles({
Need to check after merging of https://git.corp.adobe.com/CQ/universal-editor/pull/799

2024-06-27 18:36 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductpickerModal.js
> +    <Provider theme={defaultTheme} colorScheme='light'>
Should take `theme` from shared context object (now issue with dark mode)

2024-06-27 18:37 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/useConfig.js
> +  "selectionMode": "multiple",
selection-mode

2024-06-27 18:40 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/catalog-service/queries/categories.graphql.js
> +const query = `query getCategoriesInCategory($id: String!) {
It will be nice to replace on a `query-builder` that allows to avoid some duplication

2024-06-27 18:42 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductField.js
> +          <Tooltip>Select asset</Tooltip>
Select Product

2024-06-27 18:47 UTC, naydav commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductpickerModal.js
> +    const selectedProducts = productFieldValue?.split(',').map((item) => item);
It will be nice to reuse `selections-utils`

2024-06-27 18:57 UTC, naydav commented on universal-editor-product-picker/package.json
> +  "dependencies": {
Need to check latest version

2024-06-28 13:35 UTC, ahajji87 commented on universal-editor-product-picker/.github/workflows/deploy_prod.yml
I observed that the other examples have one workflow file only (post-deploy.js), I am not sure if you need these files here

2024-06-28 13:35 UTC, ahajji87 commented on universal-editor-product-picker/README.md
I think it would be helpful to describe what this extension does, how to use it, etc.

2024-06-28 13:35 UTC, ahajji87 commented on universal-editor-product-picker/src/universal-editor-ui-1/actions/graphql-proxy/index.js
> + * Copyright 2023 Adobe. All rights reserved.
2023 -> 2024

2024-06-28 13:35 UTC, ahajji87 commented on universal-editor-product-picker/src/universal-editor-ui-1/actions/host.js
> +* <license header>
missing license, in other files also

2024-06-28 13:35 UTC, ahajji87 commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/CatalogView.js
> +// @TODO
is this needed?

2024-07-18 17:18 UTC, kokoc requested changes

2024-07-18 17:18 UTC, kokoc commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductPicker.js
> +  // @TODO
TODO

2024-07-18 17:18 UTC, kokoc commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductPicker.js
> +  const [state, setState] = useState({
React recommends grouping properties when all of them are updated together - https://react.dev/learn/choosing-the-state-structure#principles-for-structuring-state

In this case, only one property of this object is usually updated. Having separate properties will reduce the code size and improve readability.

2024-07-18 17:18 UTC, kokoc commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/exc-runtime.js
> +/*
Is this needed?

2024-07-18 22:02 UTC, nitinja commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ProductPicker.js
> +        ...state,
No need to act on it, but for future: I think this type of complex state management can be effectively  done using useReducer() pattern of react hooks.

2024-08-05 16:08 UTC, fe-lix- commented on universal-editor-product-picker/src/universal-editor-ui-1/web-src/src/components/ExtensionRegistration.js
> +                dataType: 'text',
Probably there should be a default datatype `product` or `category` that can be configured.

2024-08-16 17:07 UTC, merged